apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: training-pv-pvc
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-training-disk
    fsType: ext4