apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: eu.gcr.io/sandbox-wescale/webservice-app:v4
        ports:
        - containerPort: 8080
          name: api-ws
        resources:
          limits:
            memory: "40Mi"
            cpu: "200m"
          requests:
            memory: "40Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: rest-api-ws
  selector:
    app: webservice
  type: NodePort
