version: '2'

services:
  webservice:
    image: my-back-app:v1
    networks:
      - web
    expose:
      - "8080"
    labels:
      - "traefik.backend=webservice"
      - "traefik.frontend.rule=Host:webservice.docker.localhost"
  front:
    image: front-app:v1
    networks:
      - web
    expose:
      - "3000"
    labels:
      - "traefik.backend=front"
      - "traefik.frontend.rule=Host:front.docker.localhost"

networks:
  web:
    external:
      name: traefik_webgateway
